// lib/anthropic.ts — minimal Anthropic SDK wrapper used by the streaming
// rationale fallback endpoint at `app/api/rationale/[projectId]/route.ts`.
//
// Production rationale is generated by Computer's Ranker agent and written
// straight to `pathfinder.projects.rationale` via Supabase MCP. This wrapper
// only fires when the demo opens a project the Ranker hasn't reached yet.
//
// Cloud-only. Never import from `lib/scoring.ts` (which must stay pure).

import Anthropic from '@anthropic-ai/sdk';

export const RATIONALE_MODEL = process.env.PF_RATIONALE_MODEL ?? 'claude-sonnet-4-6';
const MAX_TOKENS = 800;

const apiKey = process.env.ANTHROPIC_API_KEY;

// Defer the throw until first use so build-time imports don't blow up when
// the env var isn't set (for example during `vitest run` of the pure scoring
// module). Callers should still expect a hard failure at call time.
let _client: Anthropic | null = null;

export function anthropic(): Anthropic {
  if (_client) return _client;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY is not set');
  }
  _client = new Anthropic({ apiKey });
  return _client;
}

/**
 * Async iterator yielding rationale text deltas for the given prompt + project.
 * The endpoint pipes the deltas through an SSE response.
 */
export async function* streamRationaleDeltas(args: {
  systemPrompt: string;
  userPrompt: string;
  model?: string;
  maxTokens?: number;
}): AsyncGenerator<string, void, unknown> {
  const client = anthropic();
  const stream = client.messages.stream({
    model: args.model ?? RATIONALE_MODEL,
    max_tokens: args.maxTokens ?? MAX_TOKENS,
    system: args.systemPrompt,
    messages: [{ role: 'user', content: args.userPrompt }],
  });

  for await (const event of stream) {
    if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') {
      const text = event.delta.text;
      if (text) yield text;
    }
  }
}

/**
 * One-shot non-streaming completion. Currently unused by the endpoint but
 * kept for parity with the prototype's caching path / for tests.
 */
export async function completeRationale(args: {
  systemPrompt: string;
  userPrompt: string;
  model?: string;
  maxTokens?: number;
}): Promise<string> {
  const client = anthropic();
  const res = await client.messages.create({
    model: args.model ?? RATIONALE_MODEL,
    max_tokens: args.maxTokens ?? MAX_TOKENS,
    system: args.systemPrompt,
    messages: [{ role: 'user', content: args.userPrompt }],
  });
  return res.content
    .map((block) => (block.type === 'text' ? block.text : ''))
    .join('')
    .trim();
}
