-- Demo Polish UX Sprint — Gate 18D.
--
-- Adds reason / suggestions / retry context to unverified leads so the
-- lead detail page can render a recovery path instead of a dead end.
--
-- Additive only — no DROP, no destructive ALTER. Existing rows keep
-- the columns NULL; the verifier agent (and the new retry endpoint)
-- backfill them on the next deeper pass.

alter table pathfinder.projects
  add column if not exists verifier_failure_reason text,
  add column if not exists verifier_suggestions jsonb,
  add column if not exists verifier_attempt_count integer not null default 0,
  add column if not exists verifier_last_attempt_at timestamptz;

-- Suggestions is shaped as an array of strings; document via a comment so
-- future readers know what to expect. Postgres doesn't enforce JSON shape,
-- but the API + UI both treat null and empty-array the same.
comment on column pathfinder.projects.verifier_suggestions is
  'Array<string> of 3-5 actionable next steps generated by the verifier when verified=false.';

comment on column pathfinder.projects.verifier_failure_reason is
  '1-3 sentence per-check failure rationale, written in customer-facing language.';

comment on column pathfinder.projects.verifier_attempt_count is
  'Total deeper-pass retry attempts (Pathfinder-issued, not the cron-driven cycles).';

comment on column pathfinder.projects.verifier_last_attempt_at is
  'Timestamp of the most recent deeper-pass attempt; powers the 60s server-side debounce.';
