// app/api/rationale/[projectId]/route.ts — streaming rationale fallback.
//
// Production rationale is generated by Computer's Ranker agent and written
// to `pathfinder.projects.rationale` directly. This endpoint exists only
// for the demo case where Computer hasn't reached a project yet but the
// user clicks it — we generate a rationale via the Anthropic API, stream
// the deltas to the client as Server-Sent Events, and write the final
// text back to the project row so subsequent opens are instant.
//
// Behavior:
//   - GET / POST `/api/rationale/<id>`
//   - If `projects.rationale` exists, emit it as a single delta + close.
//   - Otherwise stream from Anthropic, write the full text back at end.
//   - SSE event format: `data: {"type":"delta","text":"..."}\n\n`
//                       `data: {"type":"done"}\n\n`
//                       `data: {"type":"error","message":"..."}\n\n`

import { NextRequest } from 'next/server';
import { promises as fs } from 'node:fs';
import path from 'node:path';

import { supabaseAdmin } from '@/lib/supabase';
import { streamRationaleDeltas } from '@/lib/anthropic';
import type { Project, Branch, Customer } from '@/lib/types';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// SSE helpers ──────────────────────────────────────────────────────────
function sseChunk(payload: unknown): Uint8Array {
  return new TextEncoder().encode(`data: ${JSON.stringify(payload)}\n\n`);
}

interface RouteContext {
  params: { projectId: string };
}

// Hardcoded fallback that mirrors `prompts/claude-ranking-rationale.md`
// closely enough that the demo doesn't break if the prompt file is missing
// at runtime (Stream 2 may have shipped it later than build).
const HARDCODED_SYSTEM_PROMPT = `You are a security-industry analyst writing the rationale block for a single project surfaced by Pathfinder, a pre-budget construction lead intelligence system operated for Zedcor Security Systems. Your output is read inside the project detail modal of an operations dashboard by a security-industry CTO and by Zedcor's branch sales leadership.

Return plain prose, three paragraphs, approximately 120 words total, followed by a separator line "HOOK:" and a single-sentence outreach hook of no more than 200 characters. No bullets. No markdown headings. No emoji. No hedging language. No marketing register.

Paragraph 1 — why this project: identify project type and operational characteristics relevant to perimeter security, vehicle barriers, surveillance camera arrays, mobile surveillance towers, or vehicle monitoring. Anchor specifics. Never invent figures.

Paragraph 2 — why now: state the project stage and what it implies for buying-cycle timing. Reference the source and posted date.

Paragraph 3 — recommended hook: name the closest Zedcor branch, the distance, and what to propose first. If a warm-intro path exists (a customer of a different branch within 50 miles), surface it.

After the third paragraph, write "HOOK:" on its own line and a single concrete sentence the salesperson can use as an opening. Voice: third-person analytical, present tense. Restraint over ornament. Never invent contacts, values, or contract numbers.`;

let _systemPromptCache: string | null = null;
async function loadSystemPrompt(): Promise<string> {
  if (_systemPromptCache) return _systemPromptCache;
  try {
    const promptPath = path.join(process.cwd(), 'prompts', 'claude-ranking-rationale.md');
    const text = await fs.readFile(promptPath, 'utf8');
    // The .md is the agent-facing brief; the model reads the whole thing as
    // its system prompt. We strip the top-level title line for cleanliness.
    const stripped = text.replace(/^#\s+.*\n/, '').trim();
    _systemPromptCache = stripped || HARDCODED_SYSTEM_PROMPT;
    return _systemPromptCache;
  } catch {
    _systemPromptCache = HARDCODED_SYSTEM_PROMPT;
    return _systemPromptCache;
  }
}

interface UserPayload {
  project: {
    id: string;
    title: string;
    summary: string | null;
    source: string;
    project_value: number | null;
    project_stage: string | null;
    posted_date: string | null;
    raw_payload_excerpt: string;
    lat: number | null;
    lon: number | null;
  };
  geography: {
    nearest_branch: {
      code: string;
      name: string;
      distance_miles: number;
      coverage_radius_miles: number;
    } | null;
    warm_customer: {
      name: string;
      served_by_branch_code: string;
      distance_miles: number;
    } | null;
  };
  zedcor_capability_matrix: string[];
}

async function buildUserPayload(project: Project): Promise<UserPayload> {
  const admin = supabaseAdmin();
  const [branchRes, customerRes] = await Promise.all([
    project.nearest_branch_id
      ? admin.from('branches').select('*').eq('id', project.nearest_branch_id).single()
      : Promise.resolve({ data: null, error: null } as { data: Branch | null; error: null }),
    project.warm_for_customer_id
      ? admin.from('customers').select('*').eq('id', project.warm_for_customer_id).single()
      : Promise.resolve({ data: null, error: null } as { data: Customer | null; error: null }),
  ]);

  const branch = (branchRes.data ?? null) as Branch | null;
  const customer = (customerRes.data ?? null) as Customer | null;

  let warmBranchCode: string | null = null;
  if (customer && customer.served_by_branch_id) {
    const { data } = await admin
      .from('branches')
      .select('code')
      .eq('id', customer.served_by_branch_id)
      .single();
    warmBranchCode = (data as { code: string } | null)?.code ?? null;
  }

  const rawSummary = project.summary ?? '';
  const rawJson = project.raw_payload ? JSON.stringify(project.raw_payload) : '';
  const excerpt = (rawSummary + (rawJson ? ` · ${rawJson}` : '')).slice(0, 500);

  return {
    project: {
      id: project.id,
      title: project.title,
      summary: project.summary,
      source: project.source,
      project_value: project.project_value,
      project_stage: project.project_stage,
      posted_date: project.posted_date,
      raw_payload_excerpt: excerpt,
      lat: project.lat,
      lon: project.lon,
    },
    geography: {
      nearest_branch: branch
        ? {
            code: branch.code,
            name: branch.name,
            distance_miles: project.distance_miles ?? 0,
            coverage_radius_miles: branch.coverage_radius_miles,
          }
        : null,
      warm_customer:
        customer && warmBranchCode
          ? {
              name: customer.name,
              served_by_branch_code: warmBranchCode,
              distance_miles: project.distance_miles ?? 0,
            }
          : null,
    },
    zedcor_capability_matrix: [
      'perimeter security',
      'vehicle barriers',
      'surveillance camera arrays',
      'mobile surveillance towers',
      'vehicle monitoring',
    ],
  };
}

async function handle(_req: NextRequest, ctx: RouteContext): Promise<Response> {
  const { projectId } = ctx.params;
  const admin = supabaseAdmin();

  // 1. Look up the project.
  const { data, error } = await admin
    .from('projects')
    .select('*')
    .eq('id', projectId)
    .single();
  const project = data as Project | null;

  if (error || !project) {
    return new Response(
      JSON.stringify({ error: 'project_not_found', detail: error?.message ?? null }),
      { status: 404, headers: { 'content-type': 'application/json' } },
    );
  }

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        // 2a. Cached path — the Ranker (or a previous fallback) already wrote it.
        if (project.rationale && project.rationale.trim().length > 0) {
          controller.enqueue(sseChunk({ type: 'delta', text: project.rationale, cached: true }));
          controller.enqueue(sseChunk({ type: 'done', cached: true }));
          controller.close();
          return;
        }

        // 2b. Live fallback — stream from Anthropic.
        const systemPrompt = await loadSystemPrompt();
        const payload = await buildUserPayload(project as Project);

        let acc = '';
        for await (const delta of streamRationaleDeltas({
          systemPrompt,
          userPrompt: JSON.stringify(payload, null, 2),
        })) {
          acc += delta;
          controller.enqueue(sseChunk({ type: 'delta', text: delta }));
        }

        // 3. Write back so subsequent opens are instant.
        const finalText = acc.trim();
        if (finalText.length > 0) {
          const update = {
            rationale: finalText,
            rationale_streamed_at: new Date().toISOString(),
          };
          await (admin.from('projects') as unknown as {
            update: (v: typeof update) => { eq: (col: string, val: string) => Promise<unknown> };
          })
            .update(update)
            .eq('id', projectId);
        }
        controller.enqueue(sseChunk({ type: 'done', cached: false }));
        controller.close();
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        controller.enqueue(sseChunk({ type: 'error', message }));
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      'content-type': 'text/event-stream; charset=utf-8',
      'cache-control': 'no-cache, no-transform',
      connection: 'keep-alive',
      'x-accel-buffering': 'no',
    },
  });
}

export async function POST(req: NextRequest, ctx: RouteContext): Promise<Response> {
  return handle(req, ctx);
}

export async function GET(req: NextRequest, ctx: RouteContext): Promise<Response> {
  return handle(req, ctx);
}
