// lib/agents/internal/hubspotNote.ts
//
// Internal onboarding Stage 9 — Internal HubSpot writer.
//
// Posts the internal HubSpot note generated by the Internal outreach
// drafter to a company record in Unicron's HubSpot tenant. Mirrors the
// existing HubSpot client shape (lib/hubspot/client.ts) so retry +
// 429-handling are inherited.
//
// Env gating:
//   - INTERNAL_HUBSPOT_API_KEY  required; missing => graceful no-op.
//   - INTERNAL_HUBSPOT_BASE_URL optional (defaults to api.hubapi.com).
//
// Lookup strategy:
//   1. If pathfinder_project_id is already mapped to a HubSpot company
//      via a custom property, reuse it (idempotent). Stage 9 stub: skip
//      to step 2.
//   2. Search companies by name (case-insensitive); use the first match.
//   3. If no match, create the company first.
//   4. Post the note attached to the company.
//
// Spec: Pathfinder/Pathfinder-Internal-Architecture.json integrations
//       (hubspot, slack, resend).

export interface InternalHubspotInput {
  company_name: string;
  note_body: string;
  fields: Record<string, string | number | null | string[]>;
}

export interface InternalHubspotResult {
  status: 'sent' | 'skipped:no_api_key' | 'created_and_sent' | 'failed';
  hubspot_company_id?: string;
  hubspot_note_id?: string;
  error?: string;
}

const DEFAULT_BASE_URL = 'https://api.hubapi.com';

function pickString(v: unknown): string {
  if (typeof v === 'string') return v;
  if (Array.isArray(v)) return v.join(', ');
  if (v === null || v === undefined) return '';
  return String(v);
}

async function hubspotFetch(
  baseUrl: string,
  token: string,
  method: string,
  path: string,
  body?: unknown,
): Promise<{ ok: boolean; status: number; data: unknown; text: string }> {
  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers: {
      authorization: `Bearer ${token}`,
      'content-type': 'application/json',
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  let data: unknown = null;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = null;
    }
  }
  return { ok: res.ok, status: res.status, data, text };
}

interface HubspotSearchResponse {
  total?: number;
  results?: Array<{ id?: string }>;
}

interface HubspotCreateResponse {
  id?: string;
}

async function findOrCreateCompany(
  baseUrl: string,
  token: string,
  name: string,
  properties: Record<string, string>,
): Promise<{ id: string; created: boolean }> {
  // Search by name.
  const search = await hubspotFetch(baseUrl, token, 'POST', '/crm/v3/objects/companies/search', {
    filterGroups: [
      {
        filters: [{ propertyName: 'name', operator: 'EQ', value: name }],
      },
    ],
    properties: ['name'],
    limit: 1,
  });
  if (search.ok) {
    const r = search.data as HubspotSearchResponse;
    if (r.total && r.results && r.results[0]?.id) {
      return { id: r.results[0].id, created: false };
    }
  }
  // Not found — create.
  const create = await hubspotFetch(baseUrl, token, 'POST', '/crm/v3/objects/companies', {
    properties: { name, ...properties },
  });
  if (!create.ok) {
    throw new Error(`hubspot_company_create_failed:${create.status}:${create.text.slice(0, 200)}`);
  }
  const r = create.data as HubspotCreateResponse;
  if (!r.id) throw new Error('hubspot_company_create_no_id');
  return { id: r.id, created: true };
}

/**
 * Write the Internal HubSpot note for a verified company.
 *
 * Graceful degradation: returns status='skipped:no_api_key' (not an
 * error) when INTERNAL_HUBSPOT_API_KEY is unset. Caller can log and
 * continue.
 */
export async function postInternalHubspotNote(
  input: InternalHubspotInput,
): Promise<InternalHubspotResult> {
  const token = process.env.INTERNAL_HUBSPOT_API_KEY;
  if (!token) {
    return { status: 'skipped:no_api_key' };
  }
  const baseUrl = process.env.INTERNAL_HUBSPOT_BASE_URL ?? DEFAULT_BASE_URL;

  try {
    const companyProps: Record<string, string> = {};
    if (input.fields.website) companyProps.website = pickString(input.fields.website);
    if (input.fields.linkedin_url) companyProps.linkedin_company_page = pickString(input.fields.linkedin_url);
    if (input.fields.hq_state) companyProps.state = pickString(input.fields.hq_state);

    const { id: companyId, created } = await findOrCreateCompany(
      baseUrl,
      token,
      input.company_name,
      companyProps,
    );

    const noteRes = await hubspotFetch(baseUrl, token, 'POST', '/crm/v3/objects/notes', {
      properties: {
        hs_note_body: input.note_body,
        hs_timestamp: String(Date.now()),
      },
      associations: [
        {
          to: { id: companyId },
          types: [
            {
              associationCategory: 'HUBSPOT_DEFINED',
              // 190 = note -> company (HubSpot's predefined association id).
              associationTypeId: 190,
            },
          ],
        },
      ],
    });
    if (!noteRes.ok) {
      return {
        status: 'failed',
        hubspot_company_id: companyId,
        error: `hubspot_note_create_failed:${noteRes.status}:${noteRes.text.slice(0, 200)}`,
      };
    }
    const note = noteRes.data as HubspotCreateResponse;
    return {
      status: created ? 'created_and_sent' : 'sent',
      hubspot_company_id: companyId,
      hubspot_note_id: note.id,
    };
  } catch (err) {
    return {
      status: 'failed',
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
